trigger:

- master
 
variables:

  tag: '$(Build.BuildId)'
 
pool:

  name: default
 
steps:
 
# 🔹 Task-1: Build Docker Image and push to ACR

- task: Docker@2

  displayName: Build and Push Docker Image

  inputs:

    containerRegistry: 'manual-aksdevopsacr-svc'

    repository: 'custom2aksnginxapp1'

    command: 'buildAndPush'

    Dockerfile: '**/Dockerfile'

    tags: |

      $(tag)

      $(Build.SourceVersion)
 
# 🔹 Debug (optional)

- bash: |

    echo "Working Directory"

    ls -R $(System.DefaultWorkingDirectory)
 
- bash: |

    echo "Before Copy Artifact Directory"

    ls -R $(Build.ArtifactStagingDirectory)
 
# 🔹 Task-2: Copy kube manifests

- task: CopyFiles@2

  displayName: Copy kube manifests

  inputs:

    SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'

    Contents: '**'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

    OverWrite: true
 
# 🔹 Debug after copy

- bash: |

    echo "After Copy Artifact Directory"

    ls -R $(Build.ArtifactStagingDirectory)
 
# 🔹 Task-3: Publish build artifacts

- task: PublishBuildArtifacts@1

  displayName: Publish kube-manifests

  inputs:

    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

    ArtifactName: 'kube-manifests'

    publishLocation: 'Container'
 